// <auto-generated />
using System;
using DataMaster.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataMaster.Data.Migrations
{
    [DbContext(typeof(DataMasterDbContext))]
    [Migration("20260911143346_AddSumberLulusanIdToCalonSiswa")]
    partial class AddSumberLulusanIdToCalonSiswa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DataMaster.Data.Entities.AuthGroup", b =>
                {
                    b.Property<int>("AuthGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthGroupId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AuthGroups");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.AuthGroupUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "AuthGroupId");

                    b.HasIndex("AuthGroupId");

                    b.ToTable("AuthGroupUsers");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.CalonSiswa", b =>
                {
                    b.Property<int>("CalonSiswaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlamatJalan")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatKecamatan")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatKelurahan")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatRt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatRw")
                        .HasColumnType("TEXT");

                    b.Property<string>("AsalSekolah")
                        .HasColumnType("TEXT");

                    b.Property<string>("Catatan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumenAkta")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumenIjazah")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumenKia")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumenKk")
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaAyah")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaIbu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nisn")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoHandphone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PekerjaanAyah")
                        .HasColumnType("TEXT");

                    b.Property<string>("PekerjaanIbu")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SiswaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SumberLulusanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("TanggalLahir")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempatLahir")
                        .HasColumnType("TEXT");

                    b.Property<string>("TingkatDituju")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CalonSiswaId");

                    b.HasIndex("SiswaId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("CalonSiswa");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Ekskul", b =>
                {
                    b.Property<int>("EkskulId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hari")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pembina")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("EkskulId");

                    b.ToTable("Ekskul");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.EkskulSiswa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EkskulId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiswaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TanggalDaftar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiswaId");

                    b.HasIndex("EkskulId", "SiswaId")
                        .IsUnique();

                    b.ToTable("EkskulSiswa");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Guru", b =>
                {
                    b.Property<int>("GuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alamat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GelarTerakhir")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jabatan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisKelamin")
                        .HasColumnType("TEXT");

                    b.Property<short?>("JumlahJamMengajar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MataPelajaranCatatan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nip")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoHandphone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NomorUrut")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StatusAktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusKeluar")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TahunAjaranMulaiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GuruId");

                    b.HasIndex("Nip");

                    b.HasIndex("NomorUrut")
                        .IsUnique();

                    b.HasIndex("TahunAjaranMulaiId");

                    b.ToTable("Guru");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.GuruMataPelajaran", b =>
                {
                    b.Property<int>("GuruMataPelajaranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuruId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MataPelajaranId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tingkat")
                        .HasColumnType("TEXT");

                    b.HasKey("GuruMataPelajaranId");

                    b.HasIndex("MataPelajaranId");

                    b.HasIndex("GuruId", "MataPelajaranId", "Tingkat")
                        .IsUnique();

                    b.ToTable("GuruMataPelajaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.JadwalPelajaran", b =>
                {
                    b.Property<int>("JadwalPelajaranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuruId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JamPelajaranId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KelasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MataPelajaranId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("JadwalPelajaranId");

                    b.HasIndex("JamPelajaranId");

                    b.HasIndex("KelasId");

                    b.HasIndex("MataPelajaranId");

                    b.HasIndex("GuruId", "JamPelajaranId", "Semester");

                    b.HasIndex("TahunAjaranId", "Semester", "KelasId", "JamPelajaranId")
                        .IsUnique();

                    b.ToTable("JadwalPelajaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.JadwalPiket", b =>
                {
                    b.Property<int>("JadwalPiketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuruId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hari")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("JadwalPiketId");

                    b.HasIndex("GuruId");

                    b.HasIndex("TahunAjaranId", "Semester", "Hari", "GuruId")
                        .IsUnique();

                    b.ToTable("JadwalPiket");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.JamPelajaran", b =>
                {
                    b.Property<int>("JamPelajaranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hari")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JamKe")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("JamMulai")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("JamSelesai")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("JamPelajaranId");

                    b.HasIndex("TahunAjaranId", "Hari", "JamKe")
                        .IsUnique();

                    b.ToTable("JamPelajaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.JamPelajaranTingkat", b =>
                {
                    b.Property<int>("JamPelajaranTingkatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JamPelajaranId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TingkatKode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JamPelajaranTingkatId");

                    b.HasIndex("JamPelajaranId", "TingkatKode")
                        .IsUnique();

                    b.ToTable("JamPelajaranTingkat");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.KalenderAkademik", b =>
                {
                    b.Property<int>("KalenderAkademikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLibur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keterangan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sasaran")
                        .HasColumnType("TEXT");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("TanggalMulai")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TanggalSelesai")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Waktu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warna")
                        .HasColumnType("TEXT");

                    b.HasKey("KalenderAkademikId");

                    b.HasIndex("TahunAjaranId", "TanggalMulai");

                    b.ToTable("KalenderAkademik");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Kelas", b =>
                {
                    b.Property<int>("KelasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("Kelompok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaKelas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tingkat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("KelasId");

                    b.HasIndex("Tingkat", "NamaKelas")
                        .IsUnique();

                    b.ToTable("Kelas");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.KepalaSekolah", b =>
                {
                    b.Property<int>("KepalaSekolahId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuruId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("KepalaSekolahId");

                    b.HasIndex("TahunAjaranId");

                    b.HasIndex("GuruId", "TahunAjaranId")
                        .IsUnique();

                    b.ToTable("KepalaSekolah");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.KurikulumAlokasi", b =>
                {
                    b.Property<int>("KurikulumAlokasiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JpPerMinggu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MataPelajaranId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TingkatKode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("KurikulumAlokasiId");

                    b.HasIndex("MataPelajaranId");

                    b.HasIndex("TahunAjaranId", "TingkatKode", "MataPelajaranId")
                        .IsUnique();

                    b.ToTable("KurikulumAlokasi");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.MataPelajaran", b =>
                {
                    b.Property<int>("MataPelajaranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kelompok")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Urutan")
                        .HasColumnType("INTEGER");

                    b.HasKey("MataPelajaranId");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.HasIndex("Nama")
                        .IsUnique();

                    b.ToTable("MataPelajaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.RiwayatAkademik", b =>
                {
                    b.Property<int>("RiwayatAkademikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KelasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiswaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RiwayatAkademikId");

                    b.HasIndex("KelasId");

                    b.HasIndex("TahunAjaranId");

                    b.HasIndex("SiswaId", "TahunAjaranId")
                        .IsUnique();

                    b.ToTable("RiwayatAkademik");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Siswa", b =>
                {
                    b.Property<int>("SiswaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlamatJalan")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatKecamatan")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatKelurahan")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatRt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlamatRw")
                        .HasColumnType("TEXT");

                    b.Property<string>("AsalSekolah")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumenAkta")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumenIjazah")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumenKia")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumenKk")
                        .HasColumnType("TEXT");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("KelasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaAyah")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaIbu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nisn")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoHandphone")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoHandphoneKedua")
                        .HasColumnType("TEXT");

                    b.Property<string>("PekerjaanAyah")
                        .HasColumnType("TEXT");

                    b.Property<string>("PekerjaanIbu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TanggalLahir")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempatLahir")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SiswaId");

                    b.HasIndex("KelasId");

                    b.HasIndex("Nis")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Siswa");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.TahunAjaran", b =>
                {
                    b.Property<int>("TahunAjaranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TahunAjaranId");

                    b.HasIndex("Nama")
                        .IsUnique();

                    b.ToTable("TahunAjaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Tingkat", b =>
                {
                    b.Property<int>("TingkatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Urutan")
                        .HasColumnType("INTEGER");

                    b.HasKey("TingkatId");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.ToTable("Tingkat");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForcePassReset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.WaliKelas", b =>
                {
                    b.Property<int>("WaliKelasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuruId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KelasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Urutan")
                        .HasColumnType("INTEGER");

                    b.HasKey("WaliKelasId");

                    b.HasIndex("TahunAjaranId");

                    b.HasIndex("GuruId", "TahunAjaranId")
                        .IsUnique();

                    b.HasIndex("KelasId", "TahunAjaranId", "Urutan")
                        .IsUnique();

                    b.ToTable("WaliKelas");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.AuthGroupUser", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.AuthGroup", "AuthGroup")
                        .WithMany("Members")
                        .HasForeignKey("AuthGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.CalonSiswa", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.Siswa", "Siswa")
                        .WithOne("CalonSiswaAsal")
                        .HasForeignKey("DataMaster.Data.Entities.CalonSiswa", "SiswaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.EkskulSiswa", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.Ekskul", "Ekskul")
                        .WithMany("EkskulSiswaList")
                        .HasForeignKey("EkskulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.Siswa", "Siswa")
                        .WithMany("EkskulSiswaList")
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekskul");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Guru", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.TahunAjaran", "TahunAjaranMulai")
                        .WithMany("GuruMulai")
                        .HasForeignKey("TahunAjaranMulaiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TahunAjaranMulai");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.GuruMataPelajaran", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.Guru", "Guru")
                        .WithMany("GuruMataPelajaranList")
                        .HasForeignKey("GuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.MataPelajaran", "MataPelajaran")
                        .WithMany("GuruMataPelajaranList")
                        .HasForeignKey("MataPelajaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guru");

                    b.Navigation("MataPelajaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.JadwalPelajaran", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.Guru", "Guru")
                        .WithMany("JadwalPelajaranList")
                        .HasForeignKey("GuruId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataMaster.Data.Entities.JamPelajaran", "JamPelajaran")
                        .WithMany("JadwalPelajaranList")
                        .HasForeignKey("JamPelajaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.Kelas", "Kelas")
                        .WithMany("JadwalPelajaranList")
                        .HasForeignKey("KelasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.MataPelajaran", "MataPelajaran")
                        .WithMany("JadwalPelajaranList")
                        .HasForeignKey("MataPelajaranId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.TahunAjaran", "TahunAjaran")
                        .WithMany("JadwalPelajaranList")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guru");

                    b.Navigation("JamPelajaran");

                    b.Navigation("Kelas");

                    b.Navigation("MataPelajaran");

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.JadwalPiket", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.Guru", "Guru")
                        .WithMany("JadwalPiketList")
                        .HasForeignKey("GuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.TahunAjaran", "TahunAjaran")
                        .WithMany("JadwalPiketList")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guru");

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.JamPelajaran", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.TahunAjaran", "TahunAjaran")
                        .WithMany("JamPelajaranList")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.JamPelajaranTingkat", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.JamPelajaran", "JamPelajaran")
                        .WithMany("BatasanTingkat")
                        .HasForeignKey("JamPelajaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JamPelajaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.KalenderAkademik", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.TahunAjaran", "TahunAjaran")
                        .WithMany("KalenderAkademikList")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.KepalaSekolah", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.Guru", "Guru")
                        .WithMany("KepalaSekolahList")
                        .HasForeignKey("GuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.TahunAjaran", "TahunAjaran")
                        .WithMany("KepalaSekolahList")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guru");

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.KurikulumAlokasi", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.MataPelajaran", "MataPelajaran")
                        .WithMany("KurikulumAlokasiList")
                        .HasForeignKey("MataPelajaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.TahunAjaran", "TahunAjaran")
                        .WithMany("KurikulumAlokasiList")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MataPelajaran");

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.RiwayatAkademik", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.Siswa", "Siswa")
                        .WithMany("RiwayatAkademikList")
                        .HasForeignKey("SiswaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.TahunAjaran", "TahunAjaran")
                        .WithMany("RiwayatAkademikList")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siswa");

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Siswa", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.Kelas", "Kelas")
                        .WithMany("SiswaList")
                        .HasForeignKey("KelasId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kelas");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.WaliKelas", b =>
                {
                    b.HasOne("DataMaster.Data.Entities.Guru", "Guru")
                        .WithMany("WaliKelasList")
                        .HasForeignKey("GuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.Kelas", "Kelas")
                        .WithMany("WaliKelasList")
                        .HasForeignKey("KelasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataMaster.Data.Entities.TahunAjaran", "TahunAjaran")
                        .WithMany("WaliKelasList")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guru");

                    b.Navigation("Kelas");

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.AuthGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Ekskul", b =>
                {
                    b.Navigation("EkskulSiswaList");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Guru", b =>
                {
                    b.Navigation("GuruMataPelajaranList");

                    b.Navigation("JadwalPelajaranList");

                    b.Navigation("JadwalPiketList");

                    b.Navigation("KepalaSekolahList");

                    b.Navigation("WaliKelasList");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.JamPelajaran", b =>
                {
                    b.Navigation("BatasanTingkat");

                    b.Navigation("JadwalPelajaranList");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Kelas", b =>
                {
                    b.Navigation("JadwalPelajaranList");

                    b.Navigation("SiswaList");

                    b.Navigation("WaliKelasList");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.MataPelajaran", b =>
                {
                    b.Navigation("GuruMataPelajaranList");

                    b.Navigation("JadwalPelajaranList");

                    b.Navigation("KurikulumAlokasiList");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.Siswa", b =>
                {
                    b.Navigation("CalonSiswaAsal");

                    b.Navigation("EkskulSiswaList");

                    b.Navigation("RiwayatAkademikList");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.TahunAjaran", b =>
                {
                    b.Navigation("GuruMulai");

                    b.Navigation("JadwalPelajaranList");

                    b.Navigation("JadwalPiketList");

                    b.Navigation("JamPelajaranList");

                    b.Navigation("KalenderAkademikList");

                    b.Navigation("KepalaSekolahList");

                    b.Navigation("KurikulumAlokasiList");

                    b.Navigation("RiwayatAkademikList");

                    b.Navigation("WaliKelasList");
                });

            modelBuilder.Entity("DataMaster.Data.Entities.User", b =>
                {
                    b.Navigation("GroupMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
